### PR TITLE
Update CNAME

### PR DESCRIPTION
**Pull request by Cronus1007**

### CODE REVIEW

**Comment by Cronus1007** [comment]
@KarishmaVanwari Thank u so much ki aapne meri pr dekh li. I am highly obliged ki aapki is pr merge se ab website hamesha secured hi khulegi.

**Comment by KarishmaVanwari** [comment]
@Cronus1007 sorryyyyy na sir, dekha nahi tha :'(
Btw drvks.in secured nahi khul rahi "shayad".

**Comment by Cronus1007** [comment]
@KarishmaVanwari pta hai.

**Comment by Cronus1007** [comment]
> @Cronus1007 sorryyyyy na sir, dekha nahi tha :'( Btw drvks.in secured nahi khul rahi "shayad".

Disappointed 🤣🤣

**Comment by KarishmaVanwari** [comment]
@Cronus1007 umm waise nth new 🥲🥲

**Pull request merged**
